### ISSUE TITLE
Add caching to influxdb query results

### ISSUE THREAD

**Issue by WyseNynja** [llamanodes/web3-proxy#105]
We had caching with our mysql stats, but when we moved to influx we deleted that code. It should be simple to add back.

One thing we need to know from the frontend team: what is the size of the query windows that you currently use?

**Comment by 0xsign** [comment]
- **daily usage**: aggregate query from start of day to the last rounded hour: query_window: last rounded hour - start of day
- **monthly usage**: aggregate query from start of month (start of day) to start of day today: query window: not sure what's best here
- **daily stats**: detailed stats query from yesterday (last rounded hour) to last rounded hour: query window: 3600
- **weekly stats**: detailed stats query from 7 days ago (last rounded hour) to last rounded hour: query window: 86400

**Comment by WyseNynja** [comment]
this load fast enough, that i think we can skip caching for now. if influx query costs end up being high, we can re-asses. but for now i'd prefer to keep RAM for jsonrpc response caches
