### ISSUE TITLE
Add chain_id to balance/:tx_hash endpoint to pick up deposit transactions

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/web3-proxy#125]
how do we handle with multiple chain-ids? One application (as I understand) only passes on requests to a single blockchain. In this case, multiplexing must occur prior to getting the API request, right? @WyseNynja

**Comment by WyseNynja** [comment]
you have to use the rpc connected to the chain you care about.

so eth payments get posted to eth.llamarpc.com, polygon payments to polygon.llamarpc.com, etc.
