### ISSUE TITLE
Premium Dashboard - Request/Byte Chart Modifications

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#13]
Context: Helps us and users deduce if their byte usage correlates with requests usage - Does one particular request take up more bytes, etc

Request | x axis
Byte | y axis
Show both Byte and Request so they overlay

Ancillary Components:
1) Modify colors of bar graphs (from various shades of pink/red) to help out those who are color blind to differentiate
2) Remove any requests/method type with "zero" on hover, so it stays in the frame. 
---Make hover Hover Method breakdown always stays in the frame - (currently, it gets cut off)

**Comment by yenicelik** [comment]
@LlamaMB this should prob be posted in the frontend repo? I will close this issue here to keep things tidy
