### ISSUE TITLE
Stripe Integration | Back-End Endpoint & Hooks

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#135]
**Objective:** Integrate Stripe into relevant backend endpoint for front-end team consumption
**Context:** Needs to accept (1) one-time payments/deposits and (2) reoccurring payments _if possible_ via an arbitrary credit balance input that draws down and is changed at end of month).

**Steps:**
- New database table for stripe deposits. 
- when inserting to that table we will also increment the total deposits in the main balance table (which is also updated by on chain deposits, admin credits, referral credits, etc). 
- All the balance checking code uses that main table so that part "plugs in" well

The frontend makes posts to stripe with a callback url of the backend endpoint. When stripe processes the payment, they post to it. Stripe sets a STRIPE_SIGNATURE header that we can verify. It's a cryptographic signature. We verify it on the backend

**Documents:**
https://stripe.com/docs/webhooks/signatures
https://stripe.com/docs/webhooks

*I'm assuming stripe tells us maximum limits when someone authorises a card for monthly billing. And that we won't need that from our own frontend. But need to check stripe docs to know

Once PR merged, we'll hand off to Front-End team. Thank you!!

**Comment by yenicelik** [comment]
https://github.com/llamanodes/web3-proxy/pull/140

**Comment by yenicelik** [comment]
We should be able to close this?
