### ISSUE TITLE
likely bug in balance stats

### ISSUE THREAD

**Issue by WyseNynja** [llamanodes/web3-proxy#147]
> [stats] balance is at 0 here while I have some requests and some cost

![Screenshot 2023-06-24 at 12 22 57](https://github.com/llamanodes/web3-proxy/assets/624221/efe059c1-c963-4e0c-a2f4-82249db27303)

**Comment by yenicelik** [comment]
fixed, will take a couple hours so the average with the wrong stats goes away
<img width="1318" alt="Screenshot 2023-06-25 at 21 32 10" src="https://github.com/llamanodes/web3-proxy/assets/8946130/24c0108d-1eba-48d1-97d6-bdb98b4dcc69">
