### ISSUE TITLE
Admin endpoint for setting user tiers

### ISSUE THREAD

**Issue by WyseNynja** [llamanodes/web3-proxy#16]
There is currently a helper script for this (`web3_proxy_cli change_user_tier_by_address`), but an admin endpoint would make this faster for our users since our admins would not need the infra team to run this command for them.

- [ ] admin endpoint
- [ ] when the tier is changed, clear the cache

**Comment by yenicelik** [comment]
This was merged (and tested in prod as I understand), should be ready to be closed
