### ISSUE TITLE
Stripe deposits history DB error

### ISSUE THREAD

**Issue by 0xsign** [llamanodes/web3-proxy#179]
```bash
GET https://ethereum-staging.llamarpc.com/user/deposits/stripe
```

Response:
```json
{
  "jsonrpc": "2.0",
  "id": null,
  "error": {
    "code": 500,
    "message": "database error!"
  }
}
```

**Comment by WyseNynja** [comment]
I believe the matching sentry error is: `database err: Type Error: A null value was encountered while decoding "date_created"`

**Comment by yenicelik** [comment]
should be resolved by https://github.com/llamanodes/web3-proxy/pull/189 , will open new issue if it re-occurs
