### ISSUE TITLE
Stats Bug | “Total Spent” discrepancies from actual RPC usage (e.g., daily spend) 

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#180]
**Context:** When creating a new LlamaNodes Premium account, the (1) Daily Average & (2) Monthly Average is showing correct based on usage. (3) Total Spent amount, however is not correct - as it shows a much higher usage than what the users has actually spent on RPC Calls. Screenshot attached for reference. 

-Incorrect = Remaining Balance: /user/balance 
-Correct = Daily usage / Monthly usage / chart: /user/stats/aggregate

-Reproduces on New Wallets w/ zero balance. Account given credit in USD, then testing initiates and issue arises.

-Reproduces on Staging and Production environments 
Staging: https://deploy-preview-849--grand-longma-8fd79c.netlify.app/admin/login
Production: https://deploy-preview-852--grand-longma-8fd79c.netlify.app/

Desired outcome: Total spent = daily usage (for new wallets)
![Screenshot 2023-07-11 at 16 31 14](https://github.com/llamanodes/web3-proxy/assets/115741159/c9dd29bb-a762-400d-bf3e-c7c8722f2930)

**Comment by WyseNynja** [comment]
Should be fixed by https://github.com/llamanodes/web3-proxy/pull/182

**Comment by WyseNynja** [comment]
that did it!
