### ISSUE TITLE
Change InfluxDB Stats | Only emit when 'Active Premium'

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#181]
**Context:** When a user has no balance, stop producing stats (for the users project/keys) so the front-end doesn't have to grey the UI - It just automatically stops producing stats. Stats to pick back up when balance is topped up. 

**Outcome:** When balance is zero ($0.00) stop producing stats for project (wallet) and its associated keys. Only activate InfluxDB data/stats when balance is above zero.

**Comment by WyseNynja** [comment]
This was done
