### ISSUE TITLE
Stipe get deposit history is implemented twice

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/web3-proxy#183]
once in payment-stripe.rs , once in payment.rs (or user.rs?). Remove the duplicate implementation, can lead to bugs

**Comment by yenicelik** [comment]
First occurrence: https://github.com/llamanodes/web3-proxy/blob/main/web3_proxy/src/frontend/users/payment.rs#L101

Second occurrence: https://github.com/llamanodes/web3-proxy/blob/main/web3_proxy/src/frontend/users/payment_stripe.rs#L26

**Comment by WyseNynja** [comment]
/user/deposits/stripe is in use. we can delete /user/balance/stripe

**Comment by WyseNynja** [comment]
#186
