### ISSUE TITLE
4337 Flag Updates | Candide Bundler Fixes

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#200]
**Contexts:** Flags have changed on Candide's end - we need to update on our end. 
**Outcome:** Fixed so LN can continue usage, doc integration, and co-marketing campaign. 

Example with the latest flags:
`docker run --net=host --rm -d ghcr.io/candidelabs/voltaire/voltaire-bundler:0.1.0a21 --entrypoint XXXXXXXXXXX --bundler_secret $BUNDLER_SECRET --rpc_url $RPC_URL --rpc_port $PORT --ethereum_node_url $NODE_URL --chain_id $CHAIN_ID --verbose`

To know about other flags:

`docker run --rm -it ghcr.io/candidelabs/voltaire/voltaire-bundler:0.1.0a21 -h`

**Comment by WyseNynja** [comment]
This was done in the provisioning repo
