### ISSUE TITLE
OP | Archive Node not showing in public dashboard

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#207]
Not showing properly in UI, not sure if its actually working or just UI. Screenshot attached

![OP Archive](https://github.com/llamanodes/web3-proxy/assets/115741159/6d4c6ab8-f7db-4f17-8ddf-d9bf2f21115f)

**Comment by WyseNynja** [comment]
If a node looks like this in the dashboard, then something is wrong with it. Report to the node maintainer in telegram rather than here for faster response.

**Comment by WyseNynja** [comment]
There is a separate issue of them not being detected as prunes rather than archives. I'll make a separate task for that
