### ISSUE TITLE
Use tokio tracing instead of log

### ISSUE THREAD

**Issue by WyseNynja** [llamanodes/web3-proxy#22]
I had tracing in the repo originally, but I was having some performance issues with it using like 50% of the app's time. Rather than fix all the fields and put "instrument" a bunch of places, I just switched to the regular logging crate and string formatting

however, now that things get sent to sentry, this is making tons of entries that are all for the same thing.

Let's put tracing back in and use fields/skip/properly.

**Comment by yenicelik** [comment]
which parts should be skipped? logging everything as trace for now

**Comment by yenicelik** [comment]
Also tracer requires any argument to have the `Debug` trait implemented. Are we ok with wrapping third-party structs and types, or shall we ignore these cases for now?

**Comment by WyseNynja** [comment]
I'm not totally sure which should be skipped. Probably at least ones that don't actually do any logging inside the function. 

For things that don't have debug impls, it's probably simplest enough to just skip them for now. Or prefix the field with % to use the toString

**Comment by yenicelik** [comment]
this can be closed now?
