### ISSUE TITLE
Limiting block ranges of eth_getLogs request

### ISSUE THREAD

**Issue by kaliubuntu0206** [llamanodes/web3-proxy#231]
Hello,

I think it would be good to add an ability to limit `eth_getLogs` since this is the method which consumes CPU usage of node.

See documents of other providers

https://www.quicknode.com/docs/ethereum/eth_getLogs

> Please note that this RPC method have a block range limit of 10,000 blocks to ensure reliability, so it's best to break down queries into smaller chunks for faster responses and better error handling. For more information about the block range limit and how to avoid it, refer to this [FAQ](https://support.quicknode.com/hc/en-us/articles/10258449939473-Is-there-a-block-range-limit-for-querying-logs-and-events-)

https://docs.infura.io/networks/ethereum/json-rpc-methods/eth_getlogs#constraints

> To prevent queries from consuming too many resources, eth_getLogs requests are currently limited by three constraints:
> A maximuim of 5,000 parameters in a single request
> A maximum of 10,000 results can be returned by a single query

https://docs.bnbchain.org/docs/rpc#rpc-endpoints-for-bnb-smart-chain

> eth_getLogs is disabled on below Mainnet endpoints, please use 3rd party endpoints from [here](https://chainlist.org/chain/56). If you need to pull logs frequently, we recommend using WebSockets to push new logs to you when they are available.

**Comment by WyseNynja** [comment]
Most providers run geth while we run erigon. Erigon handles logs much better.

If this becomes a problem, we will more likely cut the request up ourselves and make this invisible to the user. I don't like everyone having to tailor their requests to their providers, so I think this would work best.  Having it cut the requests up for the backends would also let us set small ranges on nodes like geth and larger ranges on nodes like erigon.

**Comment by kaliubuntu0206** [comment]
@WyseNynja I see, but even in Erigon I think it is reckless to allow people doing log scans for entire block range ( Some people do, from the genesis block ). I haven't really seen what happens with Erigon with the full block range scan but I think it will allow some attack vectors for the node.

**Comment by WyseNynja** [comment]
added a 200k limit in 9b6cf32faac1b91b3073843711291d3ea93583ac

it should probably be configurable (overall or maybe even per backup server). and i still think automatically cutting up the range would be good. but this was a simple patch

**Comment by WyseNynja** [comment]
oops. those should be 200s, not 400s. 4ef66d1c5d37bd00d95a374fa15abf7ab1da1692

**Comment by kaliubuntu0206** [comment]
@WyseNynja This is a great patch, thank you!
