### ISSUE TITLE
eth_getBlockReceipts occasionally fails with blockHash params

### ISSUE THREAD

**Issue by kaliubuntu0206** [llamanodes/web3-proxy#232]
eth_getBlockReceipts doesn't recognize `blockHash` parameter sometimes.

Seems like one of the backend node is using outdated erigon version or maybe the erigon doesn't support querying with blockhash params like it is written in spec https://github.com/ethereum/execution-apis/issues/393.

**Comment by WyseNynja** [comment]
Is this on ETH, or on other chains too?

**Comment by kaliubuntu0206** [comment]
@WyseNynja I have tested on ETH, since the issue happens randomly, I believe it happens somewhere on the backend erigon nodes where it isn't updated to the latest RPC spec yet.

**Comment by WyseNynja** [comment]
I cannot reproduce. Every call I make works.

Can you provide an example jsonrpc request and error response?

**Comment by WyseNynja** [comment]
I found a couple servers on an old version. But with the way web3-proxy retries errors, I can only see the error when I query the server directly. Querying through web3-proxy retries on other servers for us and hides the error.

**Comment by WyseNynja** [comment]
I added the version for all the backend servers to /status and we've upgraded all of llama node's servers
