### ISSUE TITLE
Referral Program: Generate Referral Code tied to user

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/web3-proxy#24]
Tables:
- Create a `Referral Code` Table, that is tied to a `User` user_id. Table has following specs:
    - user_ids are unique
- Create a `Referrals` Table, that records any new user who joined, using the respective referral code:
    - (`referree`, `referrer`, `valid_from_state`): both are foreign keys to the User table
- `Request` Table. This table creates a log of every transaction that a user is generating. It does not store requests older than 1 minute
- Create a `Credits` Table. This is only available to premium users, who may have free extra credits (can top up and all that).
    - user_ids are unique
    - credit: BigNumber
- `Transaction` Table. This table is responsible for recording transactions that take up credits. Credits are removed from the user when the respective transaction has enough confirmations (or if the amount of transactions that can be executed is lower than the credit available). 
    - user_id
    - transaction_hash: unique
    - chain: Enum (could also be a string for now)  

New Endpoints:
- /user/referral_code
    - Generates & returns a referral code that the user can now distribute
- /signup/:referral_code
    - Creates an entry in the table that the user is now "registered". The credit counter is initialized
- /user/add-credit
    - Tops up the credit that a user has. Accepts stablecoins, and converts them into credits
- / tx
    - Registers a transaction that was confirmed (basically to remove credits)

Affected Endpoints: 
- /proxy_web3_rpc (all RPC endpoints)
    - also submits a tx_hash s.t. this can (by a subprocess) reduce credit for the submitting user
- /user/balance

Other notes:
- We might have to run a cron job to check if a user has deposited enough credits into their accounts
- We could also have an RPC counter just to double check (before each RPC call), if the referred user's credits have been replenished. Here we can also mutate the user's table after each RPC call, updating it with how many credits were consumed.

Other questions to @WyseNynja : how are credits/funds tracked? And in which currency (if there is any)?

**Comment by WyseNynja** [comment]
We don't have any code for tracking credits/funds yet.

And it's not "transactions" that use credits. It's all rpc requests that use credits. I don't think we want cron job. We should instead check the cached user data to know if they have a positive balance or not. It's cached for 10 minutes. It's fine if someone's balance goes slightly negative from 10 minutes of excess traffic. 

There is currently code that aggregates rpc request stats in a background task and sends them into mysql. It is going through a very large refactor to send stats into mysql and into influxdb. Once I merge my stat changes in, we can add code that reduces the user's balance to it. Don't worry about reducing a user's balance for now. Let's wait for my refactor to merge first. 

`/user/add-credit`: I don't think we need this. The `/tx` endpoint is what should process the *deposit* transactions and update the users deposited amounts.

Also, when the txid is saved to the database, it should also be saved with the chain_id. 

We could have a `/admin/add-credit/:user_id` endpoint that allows giving credits without a transaction.

**Comment by yenicelik** [comment]
@WyseNynja I will open a new issue for `We could have a /admin/add-credit/:user_id endpoint that allows giving credits without a transaction.`. I think this is related to withdrawal functionality (which i have a better idea of how we can easily add more acceptable tokens), but it's not a priority right now. Will close this issue as it is in the latest PR
