### ISSUE TITLE
New Tier “Out of funds” + Grandfathering Free Custom RPC Keys 

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#30]
New Tier “Out of funds” | Grandfathering Free Custom RPC Keys 

Context: To assist with the transition of current “Free Custom RPC” and to provide a ‘state’ for those who have run out of funds when using premium we’ll need an “out of fund” tier.

Free Custom RPC: users will have this triggered when PRemium is activated and the Dashboard is reserved for Premium users. This will be triggered upon the release of Premium. *We could give the Free Custom RPC users a few free USD credits, let's say 10M reqs to mitigate any discomfort during this transition. 

Out of Funds: We’ll have plenty of users who lapse on payments, so we’ll need a ‘state’/tier that applies to them when their $ runs out. 

Out of Funds Tier Components 
-Custom Endpoint (API Key) remains - but all else is the same as the free tier:
-3,000 Requests Per Minute
-50 Request Per Second
-3 Concurrent Requests per Second
-Community Support
-HTTPS and WebSocket

No
-Archive requests
-MEV Protection 
-Advanced Dashboard (goes gray)

**Comment by yenicelik** [comment]
dependent on https://github.com/llamanodes/web3-proxy/issues/37 which introduces balances

**Comment by WyseNynja** [comment]
I think https://github.com/llamanodes/web3-proxy/pull/44 also has some code for this. Is that right @yenicelik ?

I think we still need to limit archive queries and the stats dashboard for the out of funds tier. What do you think the best way to do that is, @yenicelik ? Probably look at the balance rather than the tier, right? That's on the cached user data, right?

**Comment by yenicelik** [comment]
#44 includes logic to downgrade a user from Premium, to Premium: Out of Funds. I have not modified any logic with archive queries and stats dashboards for the out of funds tier (any user can call the dashboard if they opted in). i have not touched any archive-logic. 

also, i didn't quite catch what the last two questions in your previous comment refer to?

**Comment by yenicelik** [comment]
@WyseNynja can we close this issue?
