### ISSUE TITLE
Migrate from rpc_accounting to rpc_accounting_v2 and influx

### ISSUE THREAD

**Issue by WyseNynja** [llamanodes/web3-proxy#37]
- [ ] sql migration that adds a "migrated" nullable timestamp column
- [ ] stat_v2_migration Sub command on web3_proxy_cli 
  - [ ] load a batch of rows out of the old table
  - [ ] create request metadata objects to match the old data
  - [ ] Update the batch in the old table with the current timestamp
  - [ ] Send through a channel to a stat emitter
  -

**Comment by yenicelik** [comment]
"i think it should be possible to make the new response match this gist. probably just without "page_size" "page" or "num_items""

**Comment by yenicelik** [comment]
Rewrite https://github.com/yenicelik/web3-proxy/blob/stats_v3/web3_proxy/src/stats/db_queries.rs#L259 for influxdb https://github.com/yenicelik/web3-proxy/blob/stats_v3/web3_proxy/src/stats/influxdb_queries.rs#L32

**Comment by yenicelik** [comment]
@WyseNynja will ask you for a first review on this PR (will likely take a couple iterations) https://github.com/yenicelik/web3-proxy/pull/4

**Comment by yenicelik** [comment]
Integrated from devel, so I will close this: https://github.com/llamanodes/web3-proxy/commits/devel https://github.com/llamanodes/web3-proxy/commit/0069e760408110169dc5652740df0b645f39d291
