### ISSUE TITLE
1B | Run migration stat script (script is part of stats v2 pr)

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#46]
Final Checklist - Run migration stat script (the script is part of stats v2 pr). 

The script needs one last look over but I'm pretty sure it's done. We have not run it though. Running it is part of the deploy

**Comment by yenicelik** [comment]
@WyseNynja just assigned you (to clarify that I basically won't be working on this). i'll steal some other issues if thats ok

**Comment by WyseNynja** [comment]
No problem. Once we get https://github.com/llamanodes/web3-proxy/pull/44 and some commits I have in a local branch that change some keys around, we should be ready to run the migration script

**Comment by WyseNynja** [comment]
since we only keep 90 days of data, its really just the rpc_accounting_v2 table that matters now

**Comment by WyseNynja** [comment]
i dont trust this data anymore.
