### ISSUE TITLE
1D | Confirm that when a balance runs out, rpc keys are downgraded

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#48]
1D | Final Checklist 

1) Confirm that when a balance runs out, rpc keys are downgraded to the free tier. I think this is already part of stats v2, but if not it will be simple to add

* i’ll have to change that, should be quick though (i’m doing sub-users first though)

2) Add new tiers | Found:

-https://t.me/c/1319990593/1658

-https://llamanodesworkspace.slack.com/archives/C0460F8EGUB/p1675813311735079

**Comment by yenicelik** [comment]
I will add (proper) premium tiers prior to this issue

**Comment by WyseNynja** [comment]
How do you think the downgrade tier should be selected? I can see a few ways. I think my preference is something Iike this:

- A nullable "downgrade tier id" column on each role. That way different tiers can have different downgrades.
- If the column null, then the tier is allowed even without a balance. Or maybe even balance tracking is disabled entirely. For example, we have an "effectively unlimited" tier used for some internal rpc keys that won't ever have a balance. Knowing how much that key is "costing" us would still be helpful, so I think we should still track costs.

**Comment by yenicelik** [comment]
Should be included now in: https://github.com/llamanodes/web3-proxy/pull/44

the specific merge for this is in: https://github.com/yenicelik/web3-proxy/pull/6

**Comment by yenicelik** [comment]
will close this issue to keep things clean, can open a new issue for bugs etc. (or comments in the PR)
