### ISSUE TITLE
1F | Add request costs to existing rpc graph query

### ISSUE THREAD

**Issue by LlamaMB** [llamanodes/web3-proxy#50]
1F | Final Check List - Add request costs to existing rpc graph query. 

This should be easy. https://github.com/llamanodes/web3-proxy/pull/44/files#diff-2a86e780e3d3f3d9b9eea5a64ae983154c999af874920e336a1dace03e0b3dceR54 should be included in the database (time-series will be approximate just fyi), we dont return it in the stats-view yet but should be quick as well

**Comment by LlamaMB** [comment]
Woody to add costs tags via AWS

**Comment by WyseNynja** [comment]
https://github.com/llamanodes/web3-proxy/pull/44 Will fix this. I'm going to close since we can follow along on 44
