### ISSUE TITLE
Query window should start at a multiple

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/web3-proxy#52]
Right now there is a small bug in that the very last window is not a multiple of "period". I should fix that

**Comment by yenicelik** [comment]
The last couple commits on this should fix it: https://github.com/yenicelik/web3-proxy/commit/7490688289e8247c07975593da5242090415611b

**Comment by WyseNynja** [comment]
Awesome. What was the cause?

that commit is part of https://github.com/llamanodes/web3-proxy/pull/44, right?

**Comment by yenicelik** [comment]
yes its part of #44. I'm not sure what caused it, but it's all handled by the influxdb query now (no arithmetic by me), and all outputs looked fine. I will close this for now let's re-open it when it re-occurs.
