### ISSUE TITLE
influxdb query missing columns that the old db query had

### ISSUE THREAD

**Issue by WyseNynja** [llamanodes/web3-proxy#53]
The query currently includes:
- archive_request
- error_response
- method
- query_window_timestamp
- total_frontend_requests

It is missing:
- total_response_millis
- total_response_bytes
- total_cache_hits

**Comment by yenicelik** [comment]
this is related to the influxdb bug, am diving deeper into this

**Comment by yenicelik** [comment]
This should fix it: https://github.com/yenicelik/web3-proxy/commit/7490688289e8247c07975593da5242090415611b

**Comment by WyseNynja** [comment]
Will be fixed by https://github.com/llamanodes/web3-proxy/pull/44
