### ISSUE TITLE
tests to unconver potential bug around stat counting

### ISSUE THREAD

**Issue by WyseNynja** [llamanodes/web3-proxy#56]
https://github.com/llamanodes/web3-proxy/issues/55 might help this

i noticed that for time periods, there were more opt-in stats than there were global stats. that shouldn't be possible. there must be a bug somewhere

**Comment by WyseNynja** [comment]
I've got some commits on a local branch that change some stats keys around. I think that will fix this. Will post the commits here once merged onto devel

**Comment by yenicelik** [comment]
@WyseNynja can this be closed?
