### ISSUE TITLE
Fix subuser balance logic

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/web3-proxy#65]
https://github.com/llamanodes/web3-proxy/pull/44#discussion_r1186554879

https://github.com/llamanodes/web3-proxy/pull/44#discussion_r1186610966

https://github.com/llamanodes/web3-proxy/pull/44#discussion_r1186874565

https://github.com/llamanodes/web3-proxy/pull/44#discussion_r1186874764

**Comment by yenicelik** [comment]
- [ ] Secondary users should be able to see revert logs, too
- [ ] Should we also fetch secondary keys here? (this is displayed in a separate endpoint for clear separation)
- [ ] Possible problem here. A secondary user isn't required to have a balance of their own. We are planning to disable viewing dashboards if their balance is zero though. So I think we need to also have an entry for secondary balances. Maybe a hashmap. That way we can allow a secondary user access to dashboards.

**Comment by yenicelik** [comment]
@WyseNynja not sure if I understand the last point and where the hashmap comes into play

**Comment by yenicelik** [comment]
also reg. point 2 and 3, those are displayed on a separate endpoint `/subuser/rpc_keys`

**Comment by yenicelik** [comment]
@WyseNynja i'm also confused about the last comment here, would appreciate any more info!

**Comment by WyseNynja** [comment]
So dashboard stats should not be allowed until the user has paid us $10, but secondary user’s complicate this logic.

I think some examples will demonstrate it best

# Example 1:
- User A is the owner of Key A
- User A has a balance of $100
- User B is a collaborator for Key A
- User B has no balance

User A should be able to see their own stats
User B should be able to see stats of Key A.
User B should **not** be able to see their own stats.

# Example 2:
- User A is the owner of Key A
- User A has an balance
- User B is a collaborator for Key A
- User B has no balance

Neither User A nor B should be able to see stats

**Comment by yenicelik** [comment]
Closed in last PR

**Comment by WyseNynja** [comment]
theres still some edge cases that don't work

**Comment by WyseNynja** [comment]
I think this is fixed now
