### ISSUE TITLE
Add a column "out of funds" that we can check

### ISSUE THREAD

**Issue by yenicelik** [llamanodes/web3-proxy#66]
still to be discussed, but originated here: https://github.com/llamanodes/web3-proxy/pull/44#discussion_r1186571720

**Comment by WyseNynja** [comment]
I think looking at `authorization.checks.current_balance < $threshold` will be simplest

**Comment by yenicelik** [comment]
I added the following enum to authorization checks:
```
#[derive(Clone, Debug, Default)]
pub enum UserTier {
    #[default]
    Free,
    PrivateDemo,
    EffectivelyUnlimited,
    Unlimited,
    PremiumOutOfFunds,
    Premium,
}
```
next to balance. 

I will invalidate the item in the cache from the stats (which will trigger refetching logic for user tiers) whenever the threshold is reached.

**Comment by yenicelik** [comment]
I added the "I think looking at authorization.checks.current_balance < $threshold will be simplest" logic, I will close this issue as it is outdated as of now
